import { describe, expect, it } from "vitest";
import {
  PLAYER_NOTE_TEXT_MAX,
  changelogVersion,
  collectPlayerNotes,
  parsePlayerNotes,
  // @ts-expect-error — утилита CI на чистом JS, типов у неё нет и не нужно
} from "../release/player-notes.mjs";

// Строки журнала обновлений из раздела «Для игроков» описания PR
// (docs/35-stage4-plan.md WP31, docs/09-ci-cd.md §8.1). Цена ошибки — строка,
// которая молча не дошла до игроков, или разметка, которую игрок увидит как
// есть; поэтому формат проверяется на PR, а сборка релиза — здесь.

const body = (...lines: string[]) => ["## Что и почему", "Текст для ревьюера.", "", "## Для игроков", "<!-- подсказка шаблона -->", ...lines, "", "## Сводка для команды", "- новое: не из этого раздела"].join("\n");

describe("раздел «Для игроков»", () => {
  it("вид, площадки и текст; «все» и регистр — не ошибка; соседние разделы не читаются", () => {
    expect(parsePlayerNotes(body("- новое: Журнал обновлений — в меню «Что нового»", "* Исправлено [VK, vk]: Звук после рекламы", "- изменено [все]: Шапка под любой экран"))).toEqual({
      notes: [
        { kind: "added", platforms: [], text: "Журнал обновлений — в меню «Что нового»" },
        { kind: "fixed", platforms: ["vk"], text: "Звук после рекламы" },
        { kind: "changed", platforms: [], text: "Шапка под любой экран" },
      ],
      errors: [],
    });
  });

  it("раздел последним: хвост генератора под чертой — не строки", () => {
    const tail = ["## Для игроков", "- новое: Журнал", "", "🤖 Generated with [Claude Code](https://claude.com/claude-code)", "", "https://claude.ai/code/session_01Abc", "", "---", "_Generated by [Claude Code](https://claude.ai/code/session_01Abc)_"].join("\n");
    expect(parsePlayerNotes(tail)).toEqual({ notes: [{ kind: "added", platforms: [], text: "Журнал" }], errors: [] });
  });

  it("нет раздела, пустой раздел или «нет» — ни строк, ни ошибок", () => {
    expect(parsePlayerNotes("## Что и почему\nТекст")).toEqual({ notes: [], errors: [] });
    expect(parsePlayerNotes(body())).toEqual({ notes: [], errors: [] });
    expect(parsePlayerNotes(body("нет"))).toEqual({ notes: [], errors: [] });
    expect(parsePlayerNotes(null)).toEqual({ notes: [], errors: [] });
  });

  it("ошибки называют строку и что не так; подпись генератора — не строка", () => {
    const { notes, errors } = parsePlayerNotes(
      body("- странное: вид", "просто текст", "- исправлено [ok]: площадка", "- новое:   ", "- новое: `код` в тексте", `- новое: ${"x".repeat(PLAYER_NOTE_TEXT_MAX + 1)}`, "- новое: Годная строка", "", "🤖 Generated with [Claude Code](https://claude.com/claude-code)"),
    );
    expect(notes).toEqual([{ kind: "added", platforms: [], text: "Годная строка" }]);
    expect(errors).toHaveLength(6);
    expect(errors[0]).toContain("«- странное: вид»");
    expect(errors[1]).toContain("ожидается");
    expect(errors[2]).toContain("а не ok");
    expect(errors[3]).toContain("что изменилось");
    expect(errors[4]).toContain("разметку");
    expect(errors[5]).toContain("длиннее");
  });
});

describe("сборка строк выпуска", () => {
  const pr = (number: number, mergedAt: string | null, lines: string[], patch: Record<string, unknown> = {}) => ({
    number,
    body: body(...lines),
    merged_at: mergedAt,
    merge_commit_sha: `sha${String(number)}`,
    head: { ref: `cloud/x${String(number)}` },
    base: { ref: "dev" },
    ...patch,
  });

  it("только влитые PR выпуска по порядку мерджа; служебные и повторы — мимо; ключ — номер PR и строка", () => {
    const pullRequests = [
      pr(12, "2026-09-30T12:00:00Z", ["- исправлено [vk]: Звук"]),
      pr(11, "2026-09-30T10:00:00Z", ["- новое: Журнал", "- изменено: Шапка"]),
      pr(11, "2026-09-30T10:00:00Z", ["- новое: Журнал", "- изменено: Шапка"]),
      pr(13, null, ["- новое: Не влит"]),
      pr(14, "2026-09-29T10:00:00Z", ["- новое: Из прошлого выпуска"], { merge_commit_sha: "old" }),
      pr(15, "2026-09-30T13:00:00Z", ["- новое: Релизный PR"], { head: { ref: "dev" }, base: { ref: "main" } }),
    ];
    const { entries, warnings } = collectPlayerNotes(pullRequests, new Set(["sha11", "sha12", "sha13", "sha15"]));
    expect(entries).toEqual([
      { key: "pr-11-1", pr: 11, kind: "added", platforms: [], text: "Журнал" },
      { key: "pr-11-2", pr: 11, kind: "changed", platforms: [], text: "Шапка" },
      { key: "pr-12-1", pr: 12, kind: "fixed", platforms: ["vk"], text: "Звук" },
    ]);
    expect(warnings).toEqual([]);
  });

  it("описание испортили после мерджа — строка пропускается с предупреждением, остальные идут", () => {
    const { entries, warnings } = collectPlayerNotes([pr(21, "2026-09-30T10:00:00Z", ["- чудо: сломано", "- новое: Живая"])], new Set(["sha21"]));
    expect(entries).toEqual([{ key: "pr-21-1", pr: 21, kind: "added", platforms: [], text: "Живая" }]);
    expect(warnings[0]).toContain("PR #21");
  });

  it("версия журнала — номер выпуска без предрелиза", () => {
    expect(changelogVersion("v0.6.0-rc.3")).toBe("0.6.0");
    expect(changelogVersion("v0.6.0")).toBe("0.6.0");
    expect(changelogVersion("0.6.0")).toBeNull();
    expect(changelogVersion("v0.6")).toBeNull();
  });
});
